# Generated by Django 5.0.1 on 2024-01-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("the_auth", "0004_alter_login_id_alter_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chatbox",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("participants", models.ManyToManyField(to="the_auth.user")),
            ],
            options={
                "verbose_name": "Chatbox",
                "verbose_name_plural": "Chatboxes",
                "db_table": "chatboxes",
                "ordering": ["-createdAt"],
            },
        ),
    ]
