# Generated by Django 5.0.1 on 2024-01-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbox", "0002_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbox",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
