# Generated by Django 5.0.1 on 2024-01-31 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbox", "0003_alter_chatbox_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="readAt",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
