# Generated by Django 5.0.1 on 2024-01-23 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=50)),
                ("middleName", models.CharField(blank=True, max_length=50)),
                ("lastName", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50, unique=True)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userAgent", models.CharField(max_length=50)),
                ("ipAddress", models.CharField(max_length=50)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="the_auth.user"
                    ),
                ),
            ],
            options={
                "verbose_name": "Login",
                "verbose_name_plural": "Logins",
                "db_table": "logins",
                "ordering": ["-createdAt"],
            },
        ),
    ]
