# Generated by Django 5.0.1 on 2024-01-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("the_auth", "0002_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="login",
            name="userAgent",
            field=models.CharField(max_length=255),
        ),
    ]
