# Generated by Django 5.0.1 on 2024-01-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("the_auth", "0003_alter_login_useragent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="login",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
